### ISSUE TITLE
problem with the format

### ISSUE THREAD

**Issue by fjruizruano** [fstrozzi/Fastool#4]
Running fastool with:

$ fastool --append /1 file_1.fastq > file_new_1.fastq

I see that the first line from each sequence starts with ">" instead of "@".

Will we have some problem with this issue?

Thanks a lot!

**Comment by hk20013106** [comment]
Hi, I'm not one of the authors, but another Trinity user.
I found that Trinity2.3 and 2.4 will not read the ">" anymore. 
So if anyone needs to use Trinity2.3 and higher, please try the following link for editing the header line: 

https://www.biostars.org/p/141602/

**Comment by fjruizruano** [comment]
I have replace fastool for the command indicated in biostars!
Thanks for the help!
